title: ASTROMub Limited
description: Your home for binary trading strategies, risk management, and the ASTRONuri Trade Tracker.
theme: jekyll-theme-minimal # Use a simple theme as a base
markdown: kramdown
permalink: pretty
