title: ASTROMub Limited
description: Create your office presence with a free, fully-customizable GitHub Pages site â€” fast and maintainable.
theme: null
baseurl: /silver-umbrella
markdown: kramdown
# --- Social Sharing Image Defaults ---
social_image: /images/coverlogo.png
url: "https://astromub.github.io"
