title: "ASTROMub Limited"
description: "ASTRONuRi Trade Tracker All-in-One Risk Management and Website Builder. Maximize Profit, Minimize Cost."
theme: jekyll-theme-minimal
baseurl: "/silver-umbrella"
markdown: kramdown
social_image: "/images/coverlogo.png"
url: "https://astromub.github.io"
